rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^search/$', views.search, name='search'),
    url(r'^goto/$', views.track_url, name='goto'),
    url(r'^register_profile/$', views.register_profile, name='register_profile'),
    url(r'^profile/(?P<username>[\w\-]+)/$', views.profile, name='profile'),
    url(r'^profiles/$', views.list_profiles, name='list_profiles'),
    url(r'^like/$', views.like_category, name='like_category'),
    url(r'^add/$', views.auto_add_page, name='auto_add_page') ,
    url(r'^suggest/$', views.suggest_category, name='suggest_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    #url(r'^register/$', views.register, name='register'),
   #url(r'^login/$', views.user_login, name='login'),
   # url(r'^logout/$', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from rango import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page,
#if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/register_profile'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

CATEGORY_NAME_LENGTH = 128
PAGE_TITLE_LENGTH = 128

class Category(models.Model):
    name = models.CharField(max_length= CATEGORY_NAME_LENGTH, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique = True)

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=PAGE_TITLE_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)


    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)


    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Category, Page, CATEGORY_NAME_LENGTH, PAGE_TITLE_LENGTH
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length = CATEGORY_NAME_LENGTH, help_text = "Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)
    slug = forms.CharField(widget=forms.HiddenInput(), required = False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length = PAGE_TITLE_LENGTH, help_text = "Please enter the title of the Page.")
    url = forms.URLField(max_length = 200, help_text = "Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial = 0)

    class Meta:
        model = Page
        exclude = ('category',)


    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            return cleaned_data



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')
    


class UserProfileForm(forms.ModelForm):
    website = forms.URLField(required=False)
    picture = forms.ImageField(required=False)
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from rango.models import Category,Page, User, UserProfile
from rango.forms import CategoryForm,PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime
from rango.bing_search import google_search
from django.shortcuts import redirect
from django.template import RequestContext

def get_category_list(max_results=0, starts_with=''):
    cat_list = []
    if starts_with:
        cat_list = Category.objects.filter(name__istartswith=starts_with)

    if max_results > 0:
        if len(cat_list) > max_results:
            cat_list = cat_list[:max_results]
    return cat_list

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)

    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        visits = 1
        request.session['last_visit']  = last_visit_cookie

    request.session['visits'] = visits

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    top_five_pages = Page.objects.order_by('-views')[:5]
#    print(top_five_pages)
    context_dict = {'categories': category_list, 'pages': top_five_pages}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {'boldmessage':"Bro bro bro"}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
    context_dict = {}
    result_list = []

    try:
        category = Category.objects.get(slug = category_name_slug)
        category.views += 1
        category.save()

        pages = Page.objects.filter(category = category).order_by('-views')

        query=""
        if request.method == 'POST':
            query = request.POST['query'].strip()
            if query:
                result_list = google_search(query, num=10)


        context_dict['result_list'] = result_list
        context_dict['pages'] = pages
        context_dict['category'] = category
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit = True)

            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)

        if form.is_valid():
            if category:
                page = form.save(commit = False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)
        else:
            print(form.errors)
    context_dict={'form':form, 'category' : category}
    return render(request, 'rango/add_page.html', context_dict)


def search(request):
    result_list = []
    query=""
    if request.method == 'POST':
        query = request.POST['query'].strip()
        if query:
            result_list = google_search(query, num=10)

    return render(request, 'rango/search.html', {'result_list': result_list,
                                                 'query':query})

def track_url(request):
    #todo
    page_id = None
    if request.method == 'GET':
        if 'page_id' in request.GET:
            page_id = request.GET['page_id']
            print(page_id)

            try:
                page = Page.objects.get(id=page_id)
                page.views += 1
                page.save()
                return redirect(page.url)
            except Page.DoesNotExist:
                return HttpResponseRedirect(reverse('index'))
    
    return HttpResponseRedirect(reverse('index'))


@login_required
def profile(request, username):
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        return HttpResponseRedirect(reverse('index'))

    userprofile = UserProfile.objects.get_or_create(user=user)[0]
    form = UserProfileForm({'website': userprofile.website, 'picture': userprofile.picture})
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES,instance=userprofile)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect(reverse('rango:profile', args=[user.username]))
        else:
            print(form.errors)
    return render(request, 'rango/profile.html', {'userprofile':userprofile,'selecteduser':user,'profile_form': form})

@login_required
def register_profile(request):
    if request.method == "POST":
        profile_form = UserProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile = profile_form.save(commit = False)
            profile.user = request.user
            profile.save()

            return HttpResponseRedirect(reverse('index'))
        else:
            print(profile_form.errors)
            return HttpResponseRedirect(reverse('index'))
    else:
        profile_form = UserProfileForm()
        return render(request, 'registration/profile_registration.html', {'profile_form':profile_form}, RequestContext(request))

@login_required
def list_profiles(request):
    userprofile_list = UserProfile.objects.all()
    return render(request, 'rango/list_profiles.html', {'userprofile_list' : userprofile_list})

@login_required
def like_category(request):
    cat_id = None
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        likes = 0
        if cat_id:
            cat = Category.objects.get(id=int(cat_id))
            if cat:
                likes = cat.likes + 1
                cat.likes = likes
                cat.save()
    return HttpResponse(likes)

def suggest_category(request):
    cat_list = []
    starts_with = ''
    if request.method == 'GET':
        starts_with = request.GET['suggestion']
        cat_list = get_category_list(8, starts_with)
    return render(request, 'rango/cats.html', {'cats': cat_list })

@login_required
def auto_add_page(request):
    cat_id = None
    url = None
    title = None
    context_dict = {}
    if request.method == 'GET':
        cat_id = request.GET['category_id']
        url = request.GET['url']
        title = request.GET['title']
        if cat_id:
            category = Category.objects.get(id=int(cat_id))
            p = Page.objects.get_or_create(category=category, title=title, url=url)
            pages = Page.objects.filter(category=category).order_by('-views')
            # Adds our results list to the template context under name pages.
            context_dict['pages'] = pages
    return render(request, 'rango/page_list.html', context_dict)


'''
def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)

            profile.user = user

            if 'profile_photo' in request.FILES:
                profile.picture = request.FILES['profile_photo']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'rango/register.html', {'user_form':user_form,
                                                   'profile_form':profile_form,
                                                   'registered':registered})

'''

'''
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Your Rango account is disabled")


        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, 'rango/login.html', {})

'''

'''
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
'''

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    <title>Rango</title>
{% endblock %}


{% block body_block %}
    <h1>Rango says...</h1>
    <div>
        here is the about page! <br />
        <strong>{{ boldmessage }}</strong><br />
    </div>
    <div>
        <a href="/rango/">Index</a><br />
        <img src="{{ MEDIA_URL}}download.jpeg" 
             alt="Picture of Rango" /> <!-- New line -->
    </div>
    <p> visits: {{ visits }}</p>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title %}Add Category{% endblock %}

{% block body_block %}
    <div>
        <form id="category_form" method="post"
                                 action="{% url 'rango:add_category' %}">
    <h2 class="form-signin-heading"> Add a Category</h2>

            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
            {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
            {% endfor %}
            <button class="btn btn-primary" type="submit" name="submit">
                Create a Category
            </button>
        </form>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
{% if category %}
<form role="form" id="page_form" method="post" action="/rango/category/{{category.slug}}/add_page/">
    <h2 class="form-signin-heading"> Add a Page to
        <a href="/rango/category/{{category.slug}}/">
            {{ category.name }}</a></h2>
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
    {{ field.errors }}
    {{ field.help_text }}<br/>
    {{ field }}<br/>
    {% endfor %}
    <br/>
    <button class="btn btn-primary" type="submit" name="submit">
        Add Page
    </button>
</form>
{% else %}
<p>This is category does not exist.</p>
{% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="{% static 'images/favicon.ico' %}">
		<title>
			Rango - {% block title %}How to Tango with Django!{% endblock %}
		</title>
		<link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
		<link href="{% static "css/rango.css" %}" rel="stylesheet">
		<link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
	</head>
	<body>
		<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
			<button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand" href="{% url 'rango:index' %}">Rango</a>

			<div class="collapse navbar-collapse" id="navbar">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item active">
						<a class="nav-link" href="{% url 'rango:index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'rango:about' %}">About</a>
					</li>
<!--					<li class="nav-item">
						<a class="nav-link" href="{% url 'rango:search' %}">Search</a>
</li>-->

					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a>
					</li>
					<li class="nav-item">
                        <a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a>
					</li>


					{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'registration_register' %}">Register Here</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'auth_login' %}">Login</a>
					</li>
					{% endif %}
				</ul>
			</div>
		</nav>
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3 col-md-2 sidebar" id="sidebarfixed">
					<ul class="nav nav-list">
						<li class="nav-header">Type to find a category</li>
						<form>
							<li><input class="search-query form-control" type="text" name="suggestion" value="" id="suggestion" />
							</li>
						</form>
					</ul>
					<hr>
					<div id="cats">
					</div>
				</div>
				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					{% block body_block %}{% endblock %}
				</div>
			</div>
		</div>
		<!-- Bootstrap core JavaScript
	  ================================================== -->
	  <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js">
	  </script>
      <script src="{% static "js/rango-jquery.js" %}"></script>
      <script src="{% static "js/rango-ajax.js" %}"></script>
	  <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
	  </script>
	  <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js">
	  </script>
	</body>
</html>

templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width,
		initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
		<link rel="icon" href="{% static 'images/favicon.ico' %}">
		<title>
			Rango - {% block title %}How to Tango with Django!{% endblock %}
		</title>
		<!-- Bootstrap core CSS -->
		<link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"
	rel="stylesheet">
		<!-- Custom styles for this template -->
		<link href=
 "http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css"
 rel="stylesheet">
	</head>
	<body>
		<nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
			<button type="button" class="navbar-toggler hidden-sm-up"
			 data-toggle="collapse" data-target="#navbar"
			   aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Rango</a>
			<div id="navbar">
				<nav class="nav navbar-nav pull-xs-left">
					<a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
					<a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>
					<a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a>
					{% if user.is_authenticated %}
					<a class="nav-item nav-link"
	href="{% url 'rango:add_category' %}">
						Add a New Category</a>
					<a class="nav-item nav-link"
	href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
					{% else %}
					<a class="nav-item nav-link"
	href="{% url 'registration_register' %}">Register Here</a>
					<a class="nav-item nav-link"
	href="{% url 'auth_login' %}">Login</a>
					{% endif %}
				</nav>
			</div>
		</nav>
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-3 col-md-2 sidebar">
					{% block sidebar_block %}
					{% get_category_list category %}
					{% endblock %}
				</div>
				<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
					{% block body_block %}{% endblock %}
				</div>
			</div>
		</div>
		<!-- Bootstrap core JavaScript
	  ================================================== -->
	  <!-- Placed at the end of the document so the pages load faster -->
	  <script
	 src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js">
	  </script>
	  <script
  src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js">
	  </script>
	  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
	  <script
  src=
  "http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.j\
  s">
	  </script>
	</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> people like this category
            {% if user.is_authenticated %}
            <button id="likes" data-catid="{{category.id}}" class="btn btn-primary btn-sm" type="button">
                Like
            </button>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
            <div>
                <h1>Search with Rango</h1>
                <br/>
                <form class="form-inline" id="user_form" method="post" action="{% url 'rango:show_category' category.slug %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
                    </div>
                    <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
                </form>
                <div>
                    {% if result_list %}
                        <h3>Results</h3>
                        <!-- Display search results in an ordered list -->
                        <div class="list-group">
                            {% for result in result_list %}
                                <div class="list-group-item">
                                    <h4 class="list-group-item-heading">
                                        <a href="{{ result.link }}">{{ result.title }}</a>
                                    </h4>
                                    <p class="list-group-item-text">{{ result.snippet }}</p>
                                    {% if user.is_authenticated %}
                                    <div>
                                    <button data-catid="{{category.id}}"
                                        data-title="{{ result.title }}"
                                        data-url="{{ result.link }}"
                                        class="rango-add btn btn-info btn-sm"
                                        type="button">Add</button>
                                    </div>
                                    {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}


            <div id="pages">
            {% if pages %}
                <ul>
                    {% for page in pages %}
                        <li>
                            <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                            {% if page.views > 1 %}
                                ({{ page.views }} views)
                            {% elif page.views == 1 %}
                                ({{ page.views }} view)
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
        {% else %}
            <strong>No pages currently in category.</strong>
        {% endif %}
        </div>

        {% if user.is_authenticated %}
            <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
        {% endif %}
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
                <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong></li>
            {% else %}
                <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li> <strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Index
{% endblock %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>
    {% if user.is_authenticated %}
    <h1>hey there {{ user.username }}!</h1>
    {% else %}
    <h1>hey there partner! </h1>
    {% endif %}
</div>
<div class="row marketing">
    <div class="col-lg-6">
        <h4>Most Liked Categories</h4>
        <p>
        {% if categories %}
        <ul>
            {% for category in categories %}
            <li>
                <a href="{% url 'rango:show_category' category.slug %}">
                    {{ category.name }}</a>

                <span class="badge badge-pill
                    badge-primary">{{category.likes}}</span>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
        </p>
    </div>
    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        <p>
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li><a href="{{ page.url }}">{{ page.title }}</a>
                            <span class="badge badge-pill
                    badge-primary">{{page.views}}</span>

            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
        </p>
    </div>
</div>
<img src="{% static "images/download.jpeg" %}" alt="Picture of Rango" />
{% endblock %}

templates/rango/page_list.html
{% if pages %}
<ul>
    {% for page in pages %}
    <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}"\>{{ page.title }}</a></li>
    {% endfor %}
</ul>
{% else %}
<strong>No pages currently in category.</strong>
{% endif %}

templates/rango/search.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title %} Search {% endblock %}
{% block body_block %}
<div>
	<h1>Search with Rango</h1>
	<br/>
	<form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
		{% csrf_token %}
		<div class="form-group">
			<input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
		</div>
		<button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
	</form>
	<div>
		{% if result_list %}
			<h3>Results</h3>
			<!-- Display search results in an ordered list -->
			<div class="list-group">
				{% for result in result_list %}
					<div class="list-group-item">
						<h4 class="list-group-item-heading">
							<a href="{{ result.link }}">{{ result.title }}</a>
						</h4>
						<p class="list-group-item-text">{{ result.summary }}</p>
					</div>
				{% endfor %}
			</div>
		{% endif %}
	</div>
</div>
{% endblock %}